import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// import Scene from "./scene";

import dynamic from "next/dynamic";
import { Suspense } from "react";

const Scene = dynamic(() => import("./scene.js"), {
  suspense: true,
});

export default function Home() {
  
  const canvasWidth = 1000;
  const canvasHeight = 600;

  const reviews = [
    {
      id: 1,
      photo: "https://fshcdn.com/q/Jrb2KdW_qphh6IA7__256x256.jpg?w=640",
      name: "Lizabeth Moscow",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit, mollitia!",
      coords:[55,37]
    },
    {
      id: 2,
      photo: "https://fshcdn.com/q/Jrb2KdW_qphh6IA7__256x256.jpg?w=640",
      name: "Mike Smither New York",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit, mollitia!",
      coords: [40,-74]
    },
    {
      id: 3,
      photo: "https://fshcdn.com/q/Jrb2KdW_qphh6IA7__256x256.jpg?w=640",
      name: "Mike Smither Cyprus",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit, mollitia!",
      coords: [35,33]
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
      <Suspense className={styles.appScene}>
          <Scene canvasWidth={1000} canvasHeight={600} reviews={reviews}/>
      </Suspense>
      <h2>Hello world</h2>
    </div>
  );
}
